packages:
  - "apps/*"
  - "services/*"
  - "packages/*"

verifyDepsBeforeRun: false

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  esbuild: true
  sharp: true
  leveldown: set this to true or false
  core-js: set this to true or false
